
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "modpack"
  name = "test-mansion"
  description = "A test modpack to test mods."
  version = "1.11.3"
  platform = "fabric"
  license = "MIT"
  source = "https://github.com/minepkg/test-mansion"

# These are global requirements
[requirements]
  minecraft = "~1.16.2"
  fabricLoader = "*"

[dependencies]
  fabric = "*"
  i-am-very-smart = "^2.1.0+mpkg.1"
  modmenu = "^1.16.8+mpkg.2"
  roughlyenoughitems = "^5.11.0+mpkg.1"
  test-utils = "^0.1.0"

[dev]
