manifestVersion = 0

[package]
  type = "modpack"
  name = "test-mansion"
  description = "A test modpack to test mods."
  version = "1.10.0"
  platform = "fabric"
  license = "MIT"

[requirements]
  minecraft = "~1.16.2"
  fabric = "*"

[dependencies]
  fabric = "*"
  hwyla = "^1.9.23+minepkg.1"
  i-am-very-smart = "^2.1.0-minepkg.1"
  modmenu = "^1.14.6"
  roughlyenoughitems = "^5.11.0-minepkg.1"
  test-utils = "^0.0.5"

[dev]
