
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "modpack"
  name = "test-mansion"
  description = "A test modpack to test mods."
  version = "1.12.0"
  platform = "fabric"
  license = "MIT"
  source = "https://github.com/minepkg/test-mansion"

# These are global requirements
[requirements]
  minecraft = "~1.18.0"
  fabricLoader = "*"

[dependencies]
  fabric = "*"
  roughlyenoughitems = "^8.0.442"
  test-utils="^0.3.0"
  modmenu="^3.0.0"

[dev]
