manifestVersion = 0

[package]
  type = "modpack"
  name = "test-mansion"
  description = "A test modpack to test mods."
  version = "1.8.0"
  platform = "fabric"
  license = "MIT"

[requirements]
  minecraft = "~1.15.2"
  fabric = "*"

[dependencies]
  fabric = "0.0.0-a201907021938148"
  modmenu = "0.0.0-a201907110301518"
  test-utils = "0.0.1"

[hooks]
