manifestVersion = 0

[package]
  type = "modpack"
  name = "test-mansion"
  description = "A test modpack to test mods."
  version = "1.10.0"
  platform = "fabric"
  license = "MIT"

[requirements]
  minecraft = "~1.16.2"
  fabric = "*"

[dependencies]
  fabric = "*"
  modmenu = "^1.14.6"
  test-utils = "^0.0.5"
