manifestVersion = 0

[package]
  type = "modpack"
  name = "test-mansion"
  description = "A test modpack to test mods."
  version = "1.4.0"
  platform = "fabric"
  license = "MIT"

[requirements]
  minecraft = "1.14.3"
  fabric = "*"

[dependencies]
  fabric = "0.0.0-a201907021938148"
  modmenu = "0.0.0-a201907110301518"
  roughlyenoughitems = "0.0.0-a201907022040838"
  theoneprobe = "0.0.0-first"
  worldedit = "7.0.1"

[hooks]
