manifestVersion = 0

[package]
  type = "modpack"
  name = "test-mansion"
  description = "A test modpack to test mods."
  version = "1.11.2"
  platform = "fabric"
  license = "MIT"

[requirements]
  minecraft = "~1.16.2"
  fabric = "*"

[dependencies]
  fabric = "*"
  i-am-very-smart = "^2.1.0-minepkg.1"
  modmenu = "1.16.8-minepkg.2"
  roughlyenoughitems = "^5.11.0-minepkg.1"
  test-utils = "^0.1.0"

[dev]
