
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "modpack"
  name = "test-mansion"
  description = "A test modpack to test mods."
  version = "1.11.3"
  platform = "fabric"
  license = "MIT"
  source = "https://github.com/minepkg/test-mansion"

# These are global requirements
[requirements]
  minecraft = "~1.17.0"
  fabricLoader = "*"

[dependencies]
  fabric = "*"
  modmenu = "^2.0.2-0.mpkg.1"
  roughlyenoughitems = "^6.0.264-0.mpkg.2-alpha"
  test-utils = "^0.2.0"

[dev]
