
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "modpack"
  name = "test-mansion"
  description = "A test modpack to test mods."
  version = "1.15.0+1.19"
  platform = "fabric"
  license = "MIT"
  source = "https://github.com/minepkg/test-mansion"

# These are global requirements
[requirements]
  minecraft = "1.19.0 - 1.19.2"
  fabricLoader = "*"

[dependencies]
  fabric = "*"
  modmenu="^4.0.4+mpkg.1"
  roughlyenoughitems = "^9.1.587+mpkg.1"
  test-utils="0.3.2+1.19.2"

[dev]
