
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "modpack"
  name = "test-mansion"
  description = "A test modpack to test mods."
  version = "1.17.0+1.19.3"
  platform = "fabric"
  license = "MIT"
  source = "https://github.com/minepkg/test-mansion"

# These are global requirements
[requirements]
  minecraft = "1.19.3"
  fabricLoader = "*"

[dependencies]
  fabric = "*"
  modmenu="^5.0.2+mpkg.1"
  roughlyenoughitems = "^10.0.2274+mpkg.1"
  test-utils="^0.4.0+1.19.3"

[dev]
