name: 'crash test on push'
on: 
  pull_request:
  push:

jobs:
  crash-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # This step is only needed if you need to build a mod
      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
      - uses: minepkg/action-crash-test@v0
        with:
          # working-directory: '/' # optional
          no-build: true
          # minecraft: 1.18.2 # optional
